# Generated by Django 5.2.7 on 2025-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("product_description", models.CharField(max_length=20, null=True)),
                ("product_id", models.CharField(max_length=20)),
                ("quantity", models.CharField(max_length=20)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=6, max_length=8),
                ),
                ("prod_image", models.ImageField(upload_to="images/")),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
    ]
