# Generated by Django 5.2.7 on 2025-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="prod_image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
