# Generated by Django 5.1 on 2025-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(null='Nothing', upload_to='images/'),
        ),
    ]
